# Generated by Django 4.1.1 on 2022-10-25 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0002_todo_updation_time_alter_todo_status_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='id',
        ),
        migrations.AddField(
            model_name='todo',
            name='userid',
            field=models.AutoField(default=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 14, 46, 4, 976197)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='updation_time',
            field=models.DateTimeField(),
        ),
    ]
