# Generated by Django 4.1.1 on 2022-10-25 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0004_alter_todo_status_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 14, 55, 39, 812164)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='userid',
            field=models.AutoField(default=int, primary_key=True, serialize=False),
        ),
    ]
