# Generated by Django 4.1.1 on 2022-10-25 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0007_alter_todo_status_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 15, 1, 33, 499165)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='userid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
